### ISSUE TITLE
deteremine how to integrate new census data for 2020

### ISSUE THREAD

**Issue by dcarver1** [GeospatialCentroid/Colorado-EnviroScreen#7]
I've just heard this has been realeased determine 
- if we can pull from tigris or tidy census 
- how complete is the release of data 
- does this give up finer spatial resolution for some of the indicators as it is a full survey 

add other conditions to look out for as they come up.

**Comment by kriskara** [comment]
From: https://www.census.gov/programs-surveys/decennial-census/decade/2020/planning-management/release/redistricting-data-product-faqs.html

The August 12th, 2021 data release will provide the first look at the demographic characteristics of the nation by state, county, city, all the way down to the census block level, including:

Race and ethnicity.
Population 18 years and over.
Occupied and vacant housing units.
People living in group quarters like nursing homes, prisons, military barracks and college dorms.

By September 30, 2021, we will provide the states and the public with the same data in easier-to-use formats. Data for all states will be released at the same time. 

More 2020 Census population results will be available later including statistics on age, sex, race and ethnicity, and details about the center of population. The results for the U.S. Island Areas will also be provided in a separate release at a later date.

**Comment by kriskara** [comment]
From: https://www.census.gov/newsroom/blogs/director/2021/07/redistricting-data.html

The redistricting data include the first demographic and housing data from the 2020 Census that allow us to see demographic and population changes around the nation.

The redistricting data will include:

Housing unit counts
Occupancy status for housing units (occupied or vacant)
Population totals
Population totals by race
Population totals by race and Hispanic/Latino origin
Voting-age population (age 18 and older) totals by race and Hispanic/Latino origin
Population totals in group quarters by major group quarters type

We will release these data for all 50 states, the Commonwealth of Puerto Rico, and the District of Columbia. Within each, we will provide data for multiple geographies, such as:

Counties
Townships
Cities
Voting districts
School districts
Tracts
Census blocks

**Comment by kriskara** [comment]
Decennial Census P.L. 94-171 Redistricting Data

https://www.census.gov/programs-surveys/decennial-census/about/rdo/summary-files.html

This file provides data in a hierarchical sequence down to the block level.

**Comment by dcarver1** [comment]
after sept 30, check for integration with tidy census and evaluate if 
Percent disability
is present at the census block group level

**Comment by dcarver1** [comment]
We are holding off on this for now as many health related features and ejscreen variables are tied to the 2010 geographies
